AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  GenAiLexBotAliasArn:
    Type: String

Resources:
  ConnectInstance:
    Type: AWS::Connect::Instance
    Properties:
      Attributes:
        InboundCalls: true
        OutboundCalls: true
      IdentityManagementType: CONNECT_MANAGED
      InstanceAlias: gen-ai-connect-instance

  ConnectInstanceIntegration:
    Type: AWS::Connect::IntegrationAssociation
    Properties:
      InstanceId: !Ref ConnectInstance
      IntegrationArn: !Ref GenAiLexBotAliasArn
      IntegrationType: LEX_BOT

Outputs:
  ConnectInstanceId: 
    Value: !Ref ConnectInstance
  ConnectInstanceArn:
    Value: !GetAtt ConnectInstance.Arn





